FROM python:3.11.9-slim-bullseye

# Install necessary system dependencies, including ImageMagick, libgl1-mesa-glx, libglib2.0-0, and libomp5
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libomp5 \
    imagemagick \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /module_image_enhancement

# Copy and install the requirements
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the static directory for swagger.json
COPY static /module_image_enhancement/static

# Copy the testDocs directory
COPY testDocs /module_image_enhancement/testDocs

# Copy the rest of the application code
COPY . .

# Set the environment variable to ensure Flask runs in the proper directory
ENV FLASK_APP=server.py

# Expose the port Flask will run on
EXPOSE 8004

# Command to run the Flask application
CMD ["flask", "run", "--host=0.0.0.0", "--port=8004"]