services:
  backend:
    build:
      context: ./backend-document-analyzer
      dockerfile: dockerfile.prod
      ports:
        - "3001:3001"
      envirenment:
        - PORT=3001
        - NODE_ENV=production
      volumes:
        - ./src:/usr/src/app/src
