version: '3.8'

networks:
  default:

services:

  mysql-db:    
    container_name:  mysql-db
    image: mysql:latest 
    #command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db:/docker-entrypoint-initdb.d/
    networks:
      - default

  backend-document-analyzer:
    container_name: backend-document-analyzer
    # depends_on:
    #   - mysql-db
    build: ./backend-document-analyzer
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./backend-document-analyzer:/app
      - /app/node_modules
    networks:
      - default

  frontend-document-analyzer:
    container_name: frontend-document-analyzer
    # depends_on: 
      # - backend-document-analyzer
    build:
      context: ./frontend-document-analyzer
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $REACTJS_APP_LOCAL_PORT:$REACTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./frontend-document-analyzer:/app
      - /app/node_modules
      
    networks:
      - default
  
  module-upload:
    container_name: module-upload
    build: 
      context: ./module_upload
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MODULE_UPLOAD_LOCAL_PORT:$MODULE_UPLOAD_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./module_upload:/app      
    networks:
      - default

volumes: 
  mysql-volume: