FROM python:3.8-slim-buster

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libmagic1 \
    libmagic-dev \
    wget \
    gnupg \
    unzip \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcairo2 \
    libcups2 \
    libcurl4 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libu2f-udev \
    libvulkan1 \
    libx11-6 \
    libxcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install coverage

# Copy the rest of the application code
COPY . .

# Copy the static directory for swagger.json
COPY static /module_upload/static
COPY testDocs /module_upload/testDocs

# Set environment variables
ENV FLASK_RUN_PORT=8009
ENV FLASK_APP=server.py  

# Expose the port the Flask app runs on
EXPOSE 8009

# # Command to run the tests and see coverage report
# RUN ["python", "run_tests.py"]

CMD ["flask", "run", "--host=0.0.0.0" , "--port=8009"]