FROM python:3.8-slim-bullseye

# Installer OpenJDK (Java) et autres paquets nécessaires
RUN apt-get update && apt-get install -y \
    openjdk-11-jdk \
    maven \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app

# Installer les dépendances Maven pour télécharger les JARs
RUN mvn dependency:get -Dartifact=commons-configuration:commons-configuration:1.10
RUN mvn dependency:copy -Dartifact=commons-configuration:commons-configuration:1.10 -DoutputDirectory=/app/libs

COPY libs /app/libs

# Installer les dépendances Python
RUN python3 -m pip install --upgrade pip \
    && pip3 install --no-cache-dir -r requirements.txt

COPY . /app

ENV FLASK_APP=openhr.py

EXPOSE 8002

CMD ["flask", "run", "--host=0.0.0.0", "--port=8002"]
