FROM python:3.8-slim-buster

# Set the working directory
WORKDIR /module_extract_data

# Copy and install the requirements
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the static directory for swagger.json
COPY static /module_extract_data/static

# Copy the rest of the application code
COPY . .

# Set the environment variable to ensure Flask runs in the proper directory
ENV FLASK_APP=server.py

# Expose the port Flask will run on
EXPOSE 8005

# Command to run the Flask application
CMD ["flask", "run", "--host=0.0.0.0", "--port=8005"]
