export const itemDescriptions = {
  DOC01: 'Maroc - Contrat de travail',
  DOC02: 'Maroc - Extrait de naissance',
  DOC03: 'Maroc - Certificat de travail',
  DOC04: 'Maroc - Radio pulmonaire',
  DOC05: 'Maroc - Dossier du personnel renseigné',
  DOC06: 'MAR - Accusé de réception du règlement interne',
  DOC07: 'Maroc - Copies diplômes légalisées',
  DOC08: 'Maroc - Copie de CIN légalisée',
  DOC09: 'Maroc - Copie de la carte CNSS',
  DOC10: 'Maroc - Photos d\'identité récentes',
  DOC11: 'Maroc - Copie d\'attestation de RIB',
  DOC12: 'Maroc - Fiche Anthropométrique',
  DOC13: 'Maroc - Copie de l\'acte de mariage',
  DOC14: 'Maroc - Curriculum Vitae',
  DOC15: 'Maroc - Procédure Confidentialité des infos',
  DOC16: 'Maroc - Autorisation & Décharge',
  DOC17: 'Maroc - Charte de bonne conduite',
  DOC20: 'Maroc - Justificatif de changement d\'adresse',
  DOC32: 'Maroc - Copie de CIN',
  DOC33: 'Maroc - Copie de l\'acte de divorce',
  DOC34: 'MyFlex - Certificat Médical',
  DOC35: 'MyFlex - Certificat de Résidence',
  DOC36: 'MyFlex - Dossier Médical /Pli confidentiel',
  DOC37: 'MyFlex - Attestation de scolarité',
  DOC38: 'MyFlex - Démission',
  DOC39: 'MyFlex - Avenant de contrat',
  DOC40: 'MyFlex - Acte de naissance Enfant',
  DOC41: 'MyFlex - Demande manuscrite',
  DOC42: 'MyFlex - demande d\'aménagement du durée',
  DOC43: 'MyFlex - Certificat de grossesse',
  DOC44: 'MyFlex - Rapport Médical',
  DOC45: 'MyFlex - Certificat d\'accouchement',
};