# Use an official Node runtime as the base image
FROM cypress/included:10.0.0

# Set the working directory in the container
WORKDIR /cypress-container

# Copy package.json and package-lock.json to the container
COPY package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port that Cypress runs on
EXPOSE 8080

# Run Cypress tests when the container starts
CMD ["npm", "run", "test:e2e"]
